// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHkQfm5mBouPRdjoclih06y5fuSEmERjo',
    appId: '1:292524733746:web:47e50e55b1b940d04b932b',
    messagingSenderId: '292524733746',
    projectId: 'morehandsapp',
    authDomain: 'morehandsapp.firebaseapp.com',
    storageBucket: 'morehandsapp.firebasestorage.app',
    measurementId: 'G-D3L57J2T2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEHxdJMpH6Lr_asmv8MOYgNW17qkfuraA',
    appId: '1:292524733746:android:048ed519ebac505d4b932b',
    messagingSenderId: '292524733746',
    projectId: 'morehandsapp',
    storageBucket: 'morehandsapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiqVrG-04xDSOwF8CfnP8NqE_IDBpIAbI',
    appId: '1:292524733746:ios:ec317164938457394b932b',
    messagingSenderId: '292524733746',
    projectId: 'morehandsapp',
    storageBucket: 'morehandsapp.firebasestorage.app',
    iosClientId: '292524733746-773r47ijihg1bbbod26je03j2fll1f0e.apps.googleusercontent.com',
    iosBundleId: 'com.morehands.app',
  );
}
